### ISSUE TITLE
ImportError: No module named pyptmalloc

### ISSUE THREAD

**Issue by TacXingXing** [cloudburst/libheap#22]
```
[For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libheap/__init__.py", line 1, in <module>
    from libheap.pyptmalloc import pyptmalloc
ImportError: No module named pyptmalloc
/home/xing/.gdbinit:5: Error in sourced command file:
Error while executing Python code.
Reading symbols from ./hungman...(no debugging symbols found)...done.
(gdb) heap -a
[!] No debugee could be found.  Attach or start a program.
Python Exception <type 'exceptions.SystemExit'> None: 
Error occurred in Python command: None
(gdb) q
```
how to fix it

**Comment by cloudburst** [comment]
Does `/usr/local/lib/python2.7/dist-packages/libheap/pyptmalloc.py` exist on your setup?

It looks like something is messed up with your install maybe.

**Comment by cloudburst** [comment]
Also make sure that` /usr/local/lib/python2.7/dist-packages/libheap/` is not in your python `sys.path`.  Your sys.path should just be `/usr/local/lib/python2.7/dist-packages/`

```python
pwndbg> python import libheap
pwndbg> python print(dir(libheap))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'frontend', 'ptmalloc', 'pydbg', 'pyptmalloc']
```

You may need to reinstall if you have done a weird upgrade path from an old libheap:

```sh
pip remove libheap
sudo rm -rf /usr/local/lib/python2.7/dist-packages/libheap/
git clone https://github.com/cloudburst/libheap
pip install ./libheap
```

**Comment by TacXingXing** [comment]
Yoo! Thank you for solving my confusing,I have installed 'libheap'  a long time ago ,when i reinstall it ,it becomes error. I uninstall it and reinstall with your method ,it works well ,Thank you very much!

**Comment by cloudburst** [comment]
Good to hear, have fun!
